disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
type_body_length:
  - 400 # 300 by default warning
  - 400 # error
file_length:
  warning: 1200 # 500 by default
  error: 1200
